language: go
go:
    - 1.9

before_install:
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/mattn/goveralls
    - go get -u github.com/alecthomas/gometalinter
    - gometalinter --install

script:
    - go build
    - gometalinter -e '_test.go' -e 'Subprocess launching with variable' ./...
    - go test -v ./...
    - go test -v -covermode=count -coverprofile=coverage.out .
    - go test -v -covermode=count -coverprofile=coverage.out ./har
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
    - ./tests.sh

env:
    global:
        secure: "Ap3x9ZlbWua+//cQ8Rbo/tNbjG9UKLLunYn6oXv83inKM6MjPv6LHuQG7qphVmqEjkfn3HttevpMOazoK1Aat+F0swAzXqBQeBK2eJhxvIQW4mZHWRSPHqFn0U6drrC4HGWcXBlPW8u8kng5wzc42gPvNRoSjk08StKl3RTA88ngPf1KIdy+cqpc5Oi/9HUfwqs5HYrPK3BDicjQUNoABj2mLbSPSvaCkEvQxj4OSsY6LHkKGw+ZK/I8mWTVJEp6WJW802Kr+ODnZ4tNGqU8LLACvTyHXxZZ3+pp+DKtTe3RfpWJHOyiMJS5X4QeIIMKJlzRSL24bKSgjGbYX/qki++uZED1+wJqOMEKnqSYn1MTQZR4XiyTLaiKYmqs8eAzSSzr8FsgtxjxnmJe9ayLC/2KcANY8NLZnj+GBa8Il2OQPT1ReiiAZDNIXTGTmPphYlO963XhA9UOHbKAXXEMGO0e/yKF3x3nEa9ek+Da3wMLDPzQi8GSgetPP3Pu/VoUfSoIAl+cKHAdbubFwY/cxvKq6jS72cd2dn2FmpSdvS6G1SDZszF954Zi4ugkQ+os0EBoYaSnOlMcbycK4U13EtMloyBBWTiomvkiWg+ZLivzZASqHguAZkzrawsSutgKXPHBNXrqkokYYIPRxA6WT7IUerzX9YkQJofmhIagYw8="

